---
abstract: 'Checks POD for common spelling mistakes'
author:
  - 'Apocalypse <APOCAL@cpan.org>'
configure_requires:
  Module::Build: 0.36
dynamic_config: 0
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Pod-Spelling-CommonMistakes
provides:
  Test::Pod::Spelling::CommonMistakes:
    file: lib/Test/Pod/Spelling/CommonMistakes.pm
    version: 0.01
requires:
  Pod::Spell::CommonMistakes: 0.01
  Test::Builder: 0.94
  Test::Pod: 1.40
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Test-Pod-Spelling-CommonMistakes
  homepage: http://search.cpan.org/dist/Test-Pod-Spelling-CommonMistakes
  license: http://dev.perl.org/licenses/
  repository: http://github.com/apocalypse/perl-test-pod-spelling-commonmistakes
version: 0.01
